### PR TITLE
cp the pnpm store

### PR DESCRIPTION
**Pull request by GTrunSec**
Fixes:  permission denied

issue output:
```
     > Progress: resolved 833, reused 61, downloaded 0, added 61
       >  EACCES  EACCES: permission denied, copyfile '/build/.pnpm-store/v3/files/74/c9e58a4b95fb42589e23fcd027b1374d2c61da1138ae1e52444096af057beb5ac788b46f70cc395e9108a781cf9d0a5a56e45919d11de0ebe453d7003b7610' -> '/build/node_modules/.pnpm/eslint-plugin-antfu@0.35.3_ycpbpc6yetojsgtrx3mwntkhsu/node_modules/_tmp_48_324add1f380348648b7b24fcecd8e85e/dist/index.cjs'
       >
       > pnpm: EACCES: permission denied, copyfile '/build/.pnpm-store/v3/files/74/c9e58a4b95fb42589e23fcd027b1374d2c61da1138ae1e52444096af057beb5ac788b46f70cc395e9108a781cf9d0a5a56e45919d11de0ebe453d7003b7610' -> '/build/node_modules/.pnpm/eslint-plugin-antfu@0.35.3_ycpbpc6yetojsgtrx3mwntkhsu/node_modules/_tmp_48_324add1f380348648b7b24fcecd8e85e/dist/index.cjs'
```

### CODE REVIEW

**Comment by nzbr** [comment]
This should probably be dependent on either `copyNodeModules` or a new option (`copyPnpmStore`?). You seem to have included the changes from #4 in here as well

**Comment by GTrunSec** [comment]
> This should probably be dependent on either copyNodeModules or a new option (copyPnpmStore?).

Hum, Yeh. Although I think it's a bit redundant.

**Comment by nzbr** [comment]
As `node_modules` directories tend to grow big quickly, I think the build time improvement is worth it for packages where it works with a symlink

**Comment by GTrunSec** [comment]
> As node_modules directories tend to grow big quickly, I think the build time improvement is worth it for packages where it works with a symlink

Sure.
But according to my observation, many projects require the directory to be readable for the yarn/npm/pnpm.

https://github.com/serokell/nix-npm-buildpackage/blob/master/default.nix#L205

**Comment by nzbr** [comment]
Hmm, how about we set make it copy by default, but make symlinking an option? It works at least with the two packages I tested

**Comment by GTrunSec** [comment]
> Hmm, how about we set make it copy by default 

this would be a good compromise. thanks

**Comment by nzbr** [comment]
Does it still work for you without the chmod?

**Comment by GTrunSec** [comment]
>  Does it still work for you without the chmod?

Yeh, still. I think to replace to `cp -RL` is better.

**Pull request merged**
